swagger: '2.0'
info:
  title: BitShares Excplorer API
  description: Exposes BitShares calls needed to explore the blockchain
  version: '1'
schemes:
  - http
  - https
produces:
  - application/json
paths:
  "/get_portfolio_ranking":
    get:
      description: Get portfolio_ranking with algo in ('RV','VOT','COMP'), limit (top N)
      operationId: api.explorer.portfolio_ranking
      parameters:
        - in: query
          name: algo
          default: RV
          type: string
          required: true
          description: algo
        - in: query
          name: limit
          default: 10
          type: integer
          required: true
          description: limit
      responses:
        '200':
          description: Array of operation data
        '500':
          description: Error processing parameters
      tags:
        - api
  "/get_ex_rate":
    get:
      description: Get exchange rate
      operationId: api.explorer.get_ex_rate
      responses:
        '200':
          description: Array of operation data
        '500':
          description: Error processing parameters
      tags:
        - api
 

